# Generated by Django 4.2.7 on 2023-11-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del autor')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del autor')),
                ('estado', models.BooleanField(default=True, verbose_name='Activo/No Activo')),
                ('instagram', models.URLField(blank=True, max_length=300, verbose_name='Instagram')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
        ),
    ]
