# Generated by Django 4.2.7 on 2023-11-11 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publi', '0002_autor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'verbose_name': 'Autor', 'verbose_name_plural': 'Autores'},
        ),
    ]
